version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/" # Location of your requirements.txt or pyproject.toml
    schedule:
      interval: "daily" # Options: daily, weekly, monthly
    open-pull-requests-limit: 5 # Prevent PRspam
