repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-xml
      - id: check-added-large-files
        args: ["--maxkb", "1000"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        language: system
        entry: pyright
        types: [python]
        stages: [manual]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.18
    hooks:
      - id: uv-lock
      - id: uv-export
        args: ["--no-group", "dev", "--output-file=requirements.txt"]
      - id: uv-export
        args: ["--all-groups", "--output-file=requirements.dev.txt"]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
