repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-xml
      - id: check-added-large-files
        args: ["--maxkb", "1000"]
  
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: ty check .
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.1
    hooks:
      - id: uv-lock
      - id: uv-export
        args: ["--no-group", "dev", "--output-file=requirements.txt"]
      - id: uv-export
        args: ["--all-groups", "--output-file=requirements.dev.txt"]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout
